---
apiVersion: networking.zengarden.space/v1
kind: CompositeIngressHost
metadata:
  name: retroboard-api-composite
  namespace: dev-retroboard-api
spec:
  baseHost: "retroboard.homelab.int.zengarden.space"
  hostPattern: "retroboard-*.homelab.int.zengarden.space"
  ingressClassName: "internal"
