---
apiVersion: networking.zengarden.space/v1
kind: CompositeIngressHost
metadata:
  name: retroboard-composite
  namespace: dev-retroboard
spec:
  baseHost: "retroboard.dev.homelab.int.zengarden.space"
  hostPattern: "retroboard-*.homelab.int.zengarden.space"
  ingressClassName: "internal"
